{% set name = "isodate" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/isodate-{{ version }}.tar.gz
  sha256: c6332cf456314b85cc3b6ea2c45a6fa417cb1fddb361f6d2ed8f4f69e843c6d1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.7

test:
  imports:
    - isodate
    - isodate.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gweis/isodate/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: An ISO 8601 date/time/duration parser and formatter.
  description: |
    This module implements ISO 8601 date, time and duration parsing. The
    implementation follows ISO8601:2004 standard, and implements only date/time
    representations mentioned in the standard.
  dev_url: https://github.com/gweis/isodate

extra:
  recipe-maintainers:
    - ocefpaf
