travis:
  secure:
    BINSTAR_TOKEN: mB0jes/k7sLAm9TCZvTWBX0/rhDNnp2mC4r6hwHwK/MEKakmYS0fX8TJ/QHF8LTzMJrVPdOEMhpA77M4dvTLScdcas3OOhiNMmKSO0AJ3RB8c6nPqiCJUB2yHK1jn8tJ5wfqoyZd4YdILsORZPApgsoGiPPlR/4VRSxIs0qkRizl6hijTnD9MRtTFqX7U9nGk6osv2F0g0utVH0tVNYwe8CWjGiGpspvTokeG8AuLj37lc9peRzOaeqkINAtJDQBpdO+jZhlS/2VNtiw3q7VZZDAUfSBaUhsAfSUKkDNrPh5lPZLOFn+yTeS4r5WhC08l8WVenAn7mwPLS5afGYcvY/HgwW3z2cVnmqXOsZx0kjo/Yhzpd526fjFehL8PcKN1m493MeH4ogdhWKY/LVxp8KhwgZZOaHuaPWkFao0sEuGbqg0sdNTx4eLDFKsuXSfEPZ7yZ63SrZLav3s4kkvY+V9b8w5Yy1MwPCvTC3FEHHXBrW/rLspd1nmfVA8b0Mfb8KXuaQJstMbZXJse7E14UnI2qagl7JKhfNjx+wy3fPtpYM7qiJL/s9YBtP2+g43Buit58SMqMCv4MwVFAxKSUFKAp3UHS85537/otdqdI6QvgoDFEC4wV/QtBbsPu871UHne/r6oIb6CIletJdIbzOM+WeI77y9O4IbWbVMprY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
